### ISSUE TITLE
RuntimeError: "LayerNormKernelImpl" not implemented for 'Half'

### ISSUE THREAD

**Issue by Hickey8** [gcouairon/zestguide#4]
Hi! appreciate your impressive work.
When I run the code you offered in Usage, it occurred an error RuntimeError: "LayerNormKernelImpl" not implemented for 'Half', when I convert the fp16 model to fp32, some similar errors occurred like RuntimeError: "clamp_scalar_cpu" not implemented for 'Half'

**Comment by gcouairon** [comment]
Hello, 
thank you, I have updated the repository with my conda environment, let me know if this helps

**Comment by RainbowZhuu** [comment]
I have the same problem, may I ask if this issue has been resolved
